# Fully Automated Firebase Setup Script
Write-Host ""
Write-Host "FULLY AUTOMATED FIREBASE SETUP" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""

# Step 1: Check if Firebase is installed
Write-Host "Step 1: Checking Firebase installation..." -ForegroundColor Yellow
if (Test-Path "node_modules\firebase") {
    Write-Host "   Firebase is installed" -ForegroundColor Green
} else {
    Write-Host "   Firebase not found, installing..." -ForegroundColor Yellow
    npm install firebase | Out-Null
    Write-Host "   Firebase installed" -ForegroundColor Green
}

Write-Host ""

# Step 2: Create .env.local if it doesn't exist
Write-Host "Step 2: Setting up .env.local file..." -ForegroundColor Yellow

if (Test-Path ".env.local") {
    Write-Host "   .env.local already exists" -ForegroundColor Yellow
    $response = Read-Host "   Do you want to update it? (y/n)"
    if ($response -ne "y") {
        Write-Host "   Keeping existing .env.local" -ForegroundColor Gray
        Write-Host ""
        Write-Host "Setup complete! Your existing config will be used." -ForegroundColor Green
        exit
    }
}

Write-Host ""
Write-Host "GET YOUR FIREBASE CONFIG:" -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Gray
Write-Host ""
Write-Host "1. Open this link in your browser:" -ForegroundColor White
Write-Host "   https://console.firebase.google.com/" -ForegroundColor Cyan
Write-Host ""
Write-Host "2. Select your project (or create a new one)" -ForegroundColor White
Write-Host ""
Write-Host "3. Click the gear icon > Project settings" -ForegroundColor White
Write-Host ""
Write-Host "4. Scroll to Your apps section" -ForegroundColor White
Write-Host ""
Write-Host "5. Click on your web app (or click the web icon to add one)" -ForegroundColor White
Write-Host ""
Write-Host "6. You will see a config object - copy the values below:" -ForegroundColor White
Write-Host ""
Write-Host "================================================================" -ForegroundColor Gray
Write-Host ""

# Get Firebase config values
$apiKey = Read-Host "Enter API Key (apiKey)"
$authDomain = Read-Host "Enter Auth Domain (authDomain)"
$projectId = Read-Host "Enter Project ID (projectId)"
$storageBucket = Read-Host "Enter Storage Bucket (storageBucket)"
$messagingSenderId = Read-Host "Enter Messaging Sender ID (messagingSenderId)"
$appId = Read-Host "Enter App ID (appId)"

Write-Host ""
Write-Host "Creating .env.local file..." -ForegroundColor Yellow

# Create .env.local content
$envContent = "# Firebase Configuration`n# Auto-generated by auto-setup-firebase.ps1`n`nVITE_FIREBASE_API_KEY=$apiKey`nVITE_FIREBASE_AUTH_DOMAIN=$authDomain`nVITE_FIREBASE_PROJECT_ID=$projectId`nVITE_FIREBASE_STORAGE_BUCKET=$storageBucket`nVITE_FIREBASE_MESSAGING_SENDER_ID=$messagingSenderId`nVITE_FIREBASE_APP_ID=$appId`n"

# Write to file
try {
    $envContent | Out-File -FilePath ".env.local" -Encoding utf8 -NoNewline
    Write-Host "   .env.local created successfully!" -ForegroundColor Green
} catch {
    Write-Host "   Error creating file: $_" -ForegroundColor Red
    exit 1
}

Write-Host ""

# Step 3: Verify Firestore setup
Write-Host "Step 3: Firestore Database Setup" -ForegroundColor Yellow
Write-Host ""
Write-Host "   You need to enable Firestore in Firebase Console:" -ForegroundColor Yellow
Write-Host ""
Write-Host "   1. Go to: https://console.firebase.google.com/project/$projectId/firestore" -ForegroundColor Cyan
Write-Host "   2. Click Create database" -ForegroundColor White
Write-Host "   3. Choose Start in test mode" -ForegroundColor White
Write-Host "   4. Select a location" -ForegroundColor White
Write-Host "   5. Click Enable" -ForegroundColor White
Write-Host ""

$firestoreDone = Read-Host "   Have you enabled Firestore? (y/n)"
if ($firestoreDone -ne "y") {
    Write-Host "   Please enable Firestore before continuing" -ForegroundColor Yellow
}

Write-Host ""

# Step 4: Security Rules
Write-Host "Step 4: Setting up Security Rules" -ForegroundColor Yellow
Write-Host ""
Write-Host "   Copy these rules to Firebase Console:" -ForegroundColor White
Write-Host ""
Write-Host "rules_version = '2';" -ForegroundColor Gray
Write-Host "service cloud.firestore {" -ForegroundColor Gray
Write-Host "  match /databases/{database}/documents {" -ForegroundColor Gray
Write-Host "    match /{document=**} {" -ForegroundColor Gray
Write-Host "      allow read, write: if true;" -ForegroundColor Gray
Write-Host "    }" -ForegroundColor Gray
Write-Host "  }" -ForegroundColor Gray
Write-Host "}" -ForegroundColor Gray
Write-Host ""
Write-Host "   1. Go to: https://console.firebase.google.com/project/$projectId/firestore/rules" -ForegroundColor Cyan
Write-Host "   2. Paste the rules above" -ForegroundColor White
Write-Host "   3. Click Publish" -ForegroundColor White
Write-Host ""

$rulesDone = Read-Host "   Have you set the security rules? (y/n)"
if ($rulesDone -ne "y") {
    Write-Host "   Please set security rules before using the app" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "================================================================" -ForegroundColor Gray
Write-Host ""
Write-Host "SETUP COMPLETE!" -ForegroundColor Green
Write-Host ""
Write-Host "Summary:" -ForegroundColor Cyan
Write-Host "   Firebase package installed" -ForegroundColor Green
Write-Host "   .env.local file created" -ForegroundColor Green
if ($firestoreDone -eq "y") {
    Write-Host "   Firestore enabled" -ForegroundColor Green
} else {
    Write-Host "   Firestore needs to be enabled" -ForegroundColor Yellow
}
if ($rulesDone -eq "y") {
    Write-Host "   Security rules set" -ForegroundColor Green
} else {
    Write-Host "   Security rules need to be set" -ForegroundColor Yellow
}
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Yellow
Write-Host "   1. Restart your dev server: npm run dev" -ForegroundColor White
Write-Host "   2. Open your app in browser" -ForegroundColor White
Write-Host "   3. Create a username and test!" -ForegroundColor White
Write-Host ""
Write-Host "Test it:" -ForegroundColor Cyan
Write-Host "   - Create a username" -ForegroundColor White
Write-Host "   - Post a comment" -ForegroundColor White
Write-Host "   - Check Firebase Console > Firestore to see your data!" -ForegroundColor White
Write-Host ""
