# Firebase Setup Script
# This will create the .env.local file for you

Write-Host "🔥 Firebase Setup Script" -ForegroundColor Cyan
Write-Host ""

# Check if .env.local already exists
if (Test-Path .env.local) {
    Write-Host "⚠️  .env.local already exists!" -ForegroundColor Yellow
    $overwrite = Read-Host "Do you want to overwrite it? (y/n)"
    if ($overwrite -ne "y") {
        Write-Host "Cancelled." -ForegroundColor Red
        exit
    }
}

Write-Host "📝 Creating .env.local file..." -ForegroundColor Yellow
Write-Host ""

# Get Firebase config from user
Write-Host "Please enter your Firebase config values:" -ForegroundColor Green
Write-Host "(You can find these in Firebase Console > Project Settings > Your apps)" -ForegroundColor Gray
Write-Host ""

$apiKey = Read-Host "Enter API Key"
$authDomain = Read-Host "Enter Auth Domain"
$projectId = Read-Host "Enter Project ID"
$storageBucket = Read-Host "Enter Storage Bucket"
$messagingSenderId = Read-Host "Enter Messaging Sender ID"
$appId = Read-Host "Enter App ID"

# Create .env.local content
$envContent = @"
# Firebase Configuration
# Generated by setup-firebase.ps1

VITE_FIREBASE_API_KEY=$apiKey
VITE_FIREBASE_AUTH_DOMAIN=$authDomain
VITE_FIREBASE_PROJECT_ID=$projectId
VITE_FIREBASE_STORAGE_BUCKET=$storageBucket
VITE_FIREBASE_MESSAGING_SENDER_ID=$messagingSenderId
VITE_FIREBASE_APP_ID=$appId
"@

# Write to file
try {
    $envContent | Out-File -FilePath .env.local -Encoding utf8 -NoNewline
    Write-Host ""
    Write-Host "✅ Successfully created .env.local!" -ForegroundColor Green
    Write-Host ""
    Write-Host "📋 Your config:" -ForegroundColor Cyan
    Write-Host $envContent
    Write-Host ""
    Write-Host "🚀 Next steps:" -ForegroundColor Yellow
    Write-Host "1. Make sure Firestore is enabled in Firebase Console" -ForegroundColor White
    Write-Host "2. Set Firestore security rules (see FIREBASE_QUICK_START.md)" -ForegroundColor White
    Write-Host "3. Restart your dev server: npm run dev" -ForegroundColor White
} catch {
    Write-Host ""
    Write-Host "❌ Error creating file: $_" -ForegroundColor Red
    Write-Host ""
    Write-Host "💡 Manual option: Create .env.local file manually and paste:" -ForegroundColor Yellow
    Write-Host $envContent
}

